version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ly_inspire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ly_inspire
      - JWT_SECRET=your-development-jwt-secret
      - ADMIN_EMAIL=admin@lyinspire.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ly_inspire
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./scrapers:/app/scrapers
    restart: unless-stopped

volumes:
  postgres_data: